[settings]
experimental = true

[shell_alias]
t = "talosctl"
k = "kubectl"
h = "helm"

[tools]
kubectl = "1.35"
helm = "4.1.0"
kubens = "0.9.5"
kubectx = "0.9.5"
k9s = "0.50.18"

[hooks]
enter = '''
source <(kubectl completion bash)
source <(helm completion bash)
source <(kubens completion bash)
source <(kubectx completion bash)
'''
