[settings]
experimental = true

[shell_alias]
t = "talosctl"
k = "kubectl"
h = "helm"

[tools]
kubectl = "1.35"
helm = "4.1.0"
kubens = "0.9.5"
kubectx = "0.9.5"
k9s = "0.50.18"

[hooks.enter]
shell = "bash"
script = '''
source <(kubectl completion bash)
source <(helm completion bash)
complete -o default -F __start_kubectl k
complete -o default -F __start_helm h
'''
